name: Upload Python Package
on:
  release:
    types: [published]
jobs:
  deploy-conda:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge
      - name: Prepare
        run: conda install anaconda-client conda-build conda-verify
      - name: Build and Upload
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda config --set anaconda_upload yes
          conda build --user microsoft .
